// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.barcamp.events.models;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.barcamp.events.db.ClassSessionRepository;
import org.barcamp.events.models.ClassSession;
import org.barcamp.events.services.ClassSessionService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ClassSessionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ClassSessionDataOnDemand: @Component;
    
    private Random ClassSessionDataOnDemand.rnd = new SecureRandom();
    
    private List<ClassSession> ClassSessionDataOnDemand.data;
    
    @Autowired
    ClassSessionService ClassSessionDataOnDemand.classSessionService;
    
    @Autowired
    ClassSessionRepository ClassSessionDataOnDemand.classSessionRepository;
    
    public ClassSession ClassSessionDataOnDemand.getNewTransientClassSession(int index) {
        ClassSession obj = new ClassSession();
        setName(obj, index);
        setRunDate(obj, index);
        return obj;
    }
    
    public void ClassSessionDataOnDemand.setName(ClassSession obj, int index) {
        String name = "name_" + index;
        if (name.length() > 25) {
            name = new Random().nextInt(10) + name.substring(1, 25);
        }
        obj.setName(name);
    }
    
    public void ClassSessionDataOnDemand.setRunDate(ClassSession obj, int index) {
        Date runDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setRunDate(runDate);
    }
    
    public ClassSession ClassSessionDataOnDemand.getSpecificClassSession(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        ClassSession obj = data.get(index);
        java.lang.Long id = obj.getId();
        return classSessionService.findClassSession(id);
    }
    
    public ClassSession ClassSessionDataOnDemand.getRandomClassSession() {
        init();
        ClassSession obj = data.get(rnd.nextInt(data.size()));
        java.lang.Long id = obj.getId();
        return classSessionService.findClassSession(id);
    }
    
    public boolean ClassSessionDataOnDemand.modifyClassSession(ClassSession obj) {
        return false;
    }
    
    public void ClassSessionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = classSessionService.findClassSessionEntries(from, to);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'ClassSession' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<org.barcamp.events.models.ClassSession>();
        for (int i = 0; i < 10; i++) {
            ClassSession obj = getNewTransientClassSession(i);
            try {
                classSessionService.saveClassSession(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            classSessionRepository.flush();
            data.add(obj);
        }
    }
    
}
