// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.barcamp.events.models;

import java.util.List;
import org.barcamp.events.db.ClassSessionRepository;
import org.barcamp.events.models.ClassSessionDataOnDemand;
import org.barcamp.events.services.ClassSessionService;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ClassSessionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ClassSessionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ClassSessionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ClassSessionIntegrationTest: @Transactional;
    
    @Autowired
    private ClassSessionDataOnDemand ClassSessionIntegrationTest.dod;
    
    @Autowired
    ClassSessionService ClassSessionIntegrationTest.classSessionService;
    
    @Autowired
    ClassSessionRepository ClassSessionIntegrationTest.classSessionRepository;
    
    @Test
    public void ClassSessionIntegrationTest.testCountAllClassSessions() {
        Assert.assertNotNull("Data on demand for 'ClassSession' failed to initialize correctly", dod.getRandomClassSession());
        long count = classSessionService.countAllClassSessions();
        Assert.assertTrue("Counter for 'ClassSession' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ClassSessionIntegrationTest.testFindClassSession() {
        ClassSession obj = dod.getRandomClassSession();
        Assert.assertNotNull("Data on demand for 'ClassSession' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ClassSession' failed to provide an identifier", id);
        obj = classSessionService.findClassSession(id);
        Assert.assertNotNull("Find method for 'ClassSession' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ClassSession' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ClassSessionIntegrationTest.testFindAllClassSessions() {
        Assert.assertNotNull("Data on demand for 'ClassSession' failed to initialize correctly", dod.getRandomClassSession());
        long count = classSessionService.countAllClassSessions();
        Assert.assertTrue("Too expensive to perform a find all test for 'ClassSession', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ClassSession> result = classSessionService.findAllClassSessions();
        Assert.assertNotNull("Find all method for 'ClassSession' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ClassSession' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ClassSessionIntegrationTest.testFindClassSessionEntries() {
        Assert.assertNotNull("Data on demand for 'ClassSession' failed to initialize correctly", dod.getRandomClassSession());
        long count = classSessionService.countAllClassSessions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ClassSession> result = classSessionService.findClassSessionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ClassSession' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ClassSession' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ClassSessionIntegrationTest.testFlush() {
        ClassSession obj = dod.getRandomClassSession();
        Assert.assertNotNull("Data on demand for 'ClassSession' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ClassSession' failed to provide an identifier", id);
        obj = classSessionService.findClassSession(id);
        Assert.assertNotNull("Find method for 'ClassSession' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyClassSession(obj);
        Integer currentVersion = obj.getVersion();
        classSessionRepository.flush();
        Assert.assertTrue("Version for 'ClassSession' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ClassSessionIntegrationTest.testUpdateClassSessionUpdate() {
        ClassSession obj = dod.getRandomClassSession();
        Assert.assertNotNull("Data on demand for 'ClassSession' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ClassSession' failed to provide an identifier", id);
        obj = classSessionService.findClassSession(id);
        boolean modified =  dod.modifyClassSession(obj);
        Integer currentVersion = obj.getVersion();
        ClassSession merged = classSessionService.updateClassSession(obj);
        classSessionRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ClassSession' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ClassSessionIntegrationTest.testSaveClassSession() {
        Assert.assertNotNull("Data on demand for 'ClassSession' failed to initialize correctly", dod.getRandomClassSession());
        ClassSession obj = dod.getNewTransientClassSession(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ClassSession' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ClassSession' identifier to be null", obj.getId());
        classSessionService.saveClassSession(obj);
        classSessionRepository.flush();
        Assert.assertNotNull("Expected 'ClassSession' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ClassSessionIntegrationTest.testDeleteClassSession() {
        ClassSession obj = dod.getRandomClassSession();
        Assert.assertNotNull("Data on demand for 'ClassSession' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ClassSession' failed to provide an identifier", id);
        obj = classSessionService.findClassSession(id);
        classSessionService.deleteClassSession(obj);
        classSessionRepository.flush();
        Assert.assertNull("Failed to remove 'ClassSession' with identifier '" + id + "'", classSessionService.findClassSession(id));
    }
    
}
